version: "3.8"

networks:
  local:
    external: false

services:
  api:
    image: globo/paredao:latest
    # ports:
    #   - 8080:8080
    networks:
      - local
    environment:
      - TZ=America/Sao_Paulo
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/paredao
      - RABBITMQ_QUEUE=test-queue
      - MONGO_URL=mongodb://root:password@mongo:27017
      - MONGO_DATABASE=paredao
      - MONGO_COLLECTION=votation
      - ENABLE_CONSUMER=false
    deploy:
      replicas: 3
    depends_on:
      - mongo
      - rabbitmq

  consumer:
    image: globo/paredao:latest
    networks:
      - local
    environment:
      - TZ=America/Sao_Paulo
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/paredao
      - RABBITMQ_QUEUE=test-queue
      - MONGO_URL=mongodb://root:password@mongo:27017
      - MONGO_DATABASE=paredao
      - MONGO_COLLECTION=votation
      - ENABLE_CONSUMER=true
    deploy:
      replicas: 1
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:5.0.28
    networks:
      - local
    environment:
      - TZ=America/Sao_Paulo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=paredao
    deploy:
      replicas: 1

  rabbitmq:
    image: rabbitmq:3
    networks:
      - local
    environment:
      - TZ=America/Sao_Paulo
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=paredao
    deploy:
      replicas: 1

  nginx:
    image: globo/nginx:1.25
    ports:
      - 80:80
    networks:
      - local
    deploy:
      replicas: 1